---
# Docker Convenience Script Can Only Be Run Once
- name: Determine if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_there
  ignore_errors: True

# https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script
- name: Run Docker Install Script
  script: files/get-docker.sh
  when: docker_there.stat.exists == False

- name: Configure Docker to use local Registry Mirror
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  register: dockerd_config
  when:
    - use_mirror is defined
    - use_mirror == True

- name: Restart Docker Daemon to apply configuration
  service:
    name: docker
    state: restarted
    enabled: yes
  when: dockerd_config.changed

- name: Add Ansible User to Docker Group
  user:
    name: ansible
    groups: docker
    append: yes

# TODO remove when all OrangePis are upgraded to 4.19 Kernel
- name: Pre-Pull some images to workaround "no matching manifest for linux/arm64/unknown in the manifest list entries"
  command: "docker pull --platform arm64 {{ item }}"
  with_list:
    - k8s.gcr.io/pause:3.1
    - docker.io/coredns/coredns:1.3.0
    - docker.io/rancher/klipper-helm:v0.1.5
    - docker.io/rancher/klipper-lb:v0.1.1
    - docker.io/traefik:1.7.9
    - docker.io/tobru/inlets-arm64:latest
    - docker.io/tobru/podstalk-arm:latest
    - docker.io/busybox:1
    - docker.io/mhutter/podstalk:2019-arm64
  tags:
    prepull
